### ISSUE TITLE
No action on iOS

### ISSUE THREAD

**Issue by MoPHL** [wymsee/cordova-imagePicker#104]
Tested on iPad 2 running iOS 9.1 and simulator running same version with cordova 5.4.0, when 
```
var options = {
   maximumImagesCount: 1,
   quality: 85
};
$cordovaImagePicker.getPictures(options)
       .then(function (results) {
          console.log("Success: " + angular.toJson(results));
    }, function (error) {
        console.log("Error: " + angular.toJson(error));
     });
```
is called, nothing happens, no errors or warnings are thrown, just...nothing. Working fine on android.

Also, after running 
```
cordova platform rm ios
cordova platform add ios
``` 
to see if re-creating the ios component would fix anything, I was shown the following error after trying to run ```cordova build ios```
```
** BUILD FAILED **


The following build commands failed:
	CompileC build/test.build/Debug-iphonesimulator/test.build/Objects-normal/i386/ELCAsset.o test/Plugins/com.synconset.imagepicker/ELCAsset.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/Volumes/ionic/test/platforms/ios/cordova/build-debug.xcconfig,-project,WhaToSee.xcodeproj,ARCHS=i386,-target,test,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Volumes/ionic/test/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Volumes/ionic/test/platforms/ios/build/sharedpch
ERROR building one of the platforms: Error: /Volumes/ionic/test/platforms/ios/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /Volumes/ionic/test/platforms/ios/cordova/build: Command failed with exit code 2
```
I then proceeded to ```cordova plugin rm com.synconset.imagepicker``` and could then run ```cordova build ios``` successfully.

**Comment by clarklight** [comment]
If you put the app into the background then open it back up again, does it open the image picker?? Cos i am having similar problem, but my situation is that if i open the image picker, nothing happens, when i put the app in the background then call it back again then the imagepicker will open up.

**Comment by MoPHL** [comment]
For me it turned out that cordova didn't install the plugin properly, after doing ```cordova platform rm ios```` followed by ```cordova platform add ios``` it started working as expected.
