### ISSUE TITLE
iOS random crash in CTPicker when calling getPictures()

### ISSUE THREAD

**Issue by mirkoevo** [wymsee/cordova-imagePicker#105]
This is the exception when calling getPictures():

2015-12-01 09:11:01.404 DreamList[11004:4417388] bool _WebTryThreadLock(bool), 0x1356da3f0: Tried to obtain the web lock from a thread other than the main thread or the web thread. This may be a result of calling to UIKit from a secondary thread. Crashing now...
1   0x195b30f18 WebThreadLock
2   0x189b5f3dc <redacted>
3   0x18972e994 <redacted>
4   0x189622048 <redacted>
5   0x189621390 <redacted>
6   0x18961b0b8 <redacted>
7   0x189c69888 <redacted>
8   0x18996c234 <redacted>
9   0x18996dd94 <redacted>
10  0x189970800 <redacted>
11  0x1896edea0 <redacted>
12  0x1000da6c4 __24-[CTPicker getPictures:]_block_invoke
13  0x1001d9ca8 _dispatch_call_block_and_release
14  0x1001d9c68 _dispatch_client_callout
15  0x1001e8ec8 _dispatch_root_queue_drain
16  0x1001e8590 _dispatch_worker_thread3
17  0x199555470 _pthread_wqthread
18  0x199555020 start_wqthread

-getPictures: (CTPicker.m)

       [self.viewController presentViewController:imagePicker animated:YES completion:NULL];   <— HERE

**Comment by DMcNamara** [comment]
Looks like you're using some fork of our plugin, the ID on this is SOSPicker not CTPicker. I think CTPicker is https://github.com/jeduan/cordova-plugin-imagepicker.
