### ISSUE TITLE
The app crash on Kitkat randomly when selecting photos

### ISSUE THREAD

**Issue by goldopuk** [wymsee/cordova-imagePicker#11]
After selecting photos and clicking the button OK, the app is crashing randomly on Android. 

It is happening on two different phones powered by Kitkat (4.4.2).
With Ice Cream Sandwich and Jelly Bean, I am not having any problem.

Is someone experiencing the same error and knows a way to solve it ?

I got this stacktrace in eclipse:

05-27 13:40:39.825: E/WindowManager(21871): android.view.WindowLeaked: Activity com.synconset.MultiImageChooserActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{421e2758 V.E..... R......D 0,0-684,324} that was originally added here
05-27 13:40:39.825: E/WindowManager(21871):     at android.view.ViewRootImpl.<init>(ViewRootImpl.java:361)
05-27 13:40:39.825: E/WindowManager(21871):     at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
05-27 13:40:39.825: E/WindowManager(21871):     at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
05-27 13:40:39.825: E/WindowManager(21871):     at android.app.Dialog.show(Dialog.java:286)
05-27 13:40:39.825: E/WindowManager(21871):     at com.synconset.MultiImageChooserActivity.selectClicked(MultiImageChooserActivity.java:305)
05-27 13:40:39.825: E/WindowManager(21871):     at com.synconset.MultiImageChooserActivity$3.onClick(MultiImageChooserActivity.java:353)
05-27 13:40:39.825: E/WindowManager(21871):     at android.view.View.performClick(View.java:4456)
05-27 13:40:39.825: E/WindowManager(21871):     at android.view.View$PerformClick.run(View.java:18462)
05-27 13:40:39.825: E/WindowManager(21871):     at android.os.Handler.handleCallback(Handler.java:733)
05-27 13:40:39.825: E/WindowManager(21871):     at android.os.Handler.dispatchMessage(Handler.java:95)
05-27 13:40:39.825: E/WindowManager(21871):     at android.os.Looper.loop(Looper.java:136)
05-27 13:40:39.825: E/WindowManager(21871):     at android.app.ActivityThread.main(ActivityThread.java:5102)
05-27 13:40:39.825: E/WindowManager(21871):     at java.lang.reflect.Method.invokeNative(Native Method)
05-27 13:40:39.825: E/WindowManager(21871):     at java.lang.reflect.Method.invoke(Method.java:515)
05-27 13:40:39.825: E/WindowManager(21871):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
05-27 13:40:39.825: E/WindowManager(21871):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
05-27 13:40:39.825: E/WindowManager(21871):     at dalvik.system.NativeStart.main(Native Method)

Thanks,

**Comment by demobo-com** [comment]
Still crash on some certain pictures. Nexus 5 running 4.4.2.
