### ISSUE TITLE
Android temporary files

### ISSUE THREAD

**Issue by razier** [wymsee/cordova-imagePicker#114]
Firstly I would like to apologize as this would be a query rather then an issue, but the readme mentioned that on android the temporary files (are often?) not removed automatically.

Is there any example on how I can check if the files still exist and remove them?

**Comment by ildr3him** [comment]
+1

**Comment by ildr3him** [comment]
@razier I delete the files using cordova-plugin-file

But I have the problem that even though i remove the files in this path:
file:///data/data/com.idbqlxjwi9dgva5gzhf/cache/
the app still gets bigger and bigger as if the files weren't deleted. Are they saved in another directory besides cache?

**Comment by razier** [comment]
@ildr3him Sorry for the late reply ( I eventually switch to a simpler method instead of using this plugin because I don't need to select multiple files ).

But also I did some digging on the source code and in MultiImageChooserActivity.java there is a function called storeImage which actually call File.createTempFile.

Based on the android documentation for File.createTempFile if the third parameter is not specified it actually stores in a temporary directory based on the system "java.io.tmpdir" system property which mention normally in unix it would be /tmp (I suppose different phone would have different value set for this)

So based on that understanding the temporary files there wouldn't affect the size of your app, so it might be something else that causes it

https://github.com/wymsee/cordova-imagePicker/blob/master/src/android/Library/src/MultiImageChooserActivity.java

http://developer.android.com/reference/java/io/File.html#createTempFile(java.lang.String, java.lang.String, java.io.File).
