### ISSUE TITLE
Want to access to icloud photo

### ISSUE THREAD

**Issue by mrdevnet** [wymsee/cordova-imagePicker#141]
Hey Admin.
just want to thanks you for providing us the best plugin.
btw, I have question: How to access to cloud photo to select those photos.
I used the standard select photo of cordova before. and It worked. but it was not possible to select mutiple photos.

thanks so much if you can update it, or let me know How can i customize your code.

**Comment by mrdevnet** [comment]
You can try to use update library with Photos library update for iOS 8 onwards with iCloud sync. 
At https://github.com/amitbobade2007/ELCImagePickerController.
Forked from latest master branch and update for support.

**Comment by Duder-onomy** [comment]
This should be re-opened. This is still a problem right now, if photos are stored on icloud then they will not show up in this image picker, but they do show up in the ios native picker. 

Related to: https://stackoverflow.com/questions/42604437/ioinc2-cordova-image-picker-not-listing-icloud-synched-photos-on-ios10-2-ip
And: https://github.com/Telerik-Verified-Plugins/ImagePicker/issues/40

Seems like @mrdevnet solved this last year. 
Going to do some investigation with the fork he mentions of ELCImagePickerController

**Comment by martijnlutgens** [comment]
@Duder-onomy Did you manage to solve this? A customer reported this problem to me and the issue is also still not fixed in [Telerik-Verified-Plugins#40](https://github.com/Telerik-Verified-Plugins/ImagePicker/issues/40). I am using Ionic, so were you able to use the ELCImagePickerController with Ionic?

**Comment by Duder-onomy** [comment]
@martijnlutgens I did not figure it out. We ended up re-platforming with react native. Sorry, hope you figure it out!
