### ISSUE TITLE
xcode 8 upgrade - Info.plist permissions error

### ISSUE THREAD

**Issue by rrubio** [wymsee/cordova-imagePicker#179]
Hi Guys,

Just upgraded to xcode 8 and it appears to break my app on open album, see below for error log. I have uninstalled and installed a number of times, also tried updating my ionic install. 

NOTE: After the xcode 8 upgrade, i had to reinstall ios-sim &  ios-deploy (again) as it wasn't being found.

ccd[1426]: [access] Refusing TCCAccessRequest for service kTCCServicePhotos and client /Users/<my_user_dir>/Library/Developer/CoreSimulator/Devices/268F812D-B91E-40A2-943B-7DCF6548CF18/data/Containers/Bundle/Application/2FCEDD36-41B6-47A8-B49D-49DC356DA9C3/gcmAPP_V2.app/gcmAPP_V2 without NSPhotoLibraryUsageDescription key

V2[1491]: [access] This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data.

**Comment by sdushay** [comment]
There is a PR to fix this in #166 that we're looking at.

**Comment by rrubio** [comment]
@sdushay thanks mate! really appreciate it.

**Comment by sdushay** [comment]
This was merged into master in #180.  It's included in release v1.1.2.
