### ISSUE TITLE
[Observation] iOS 10 issue "NSPhotoLibraryUsageDescription"

### ISSUE THREAD

**Issue by gaurav-chandra** [wymsee/cordova-imagePicker#181]
There is a small observation which prompted me to add this here. The variable adds the required message efficiently but the ios.json file, which cordova makes, has a small error: there is a space after "NSPhotoLibraryUsageDescription" entry. Due to this the build is rejected as the space is added in Info.plist file as it is. 

When I made the changes directly in XCode, it was auto corrected by XCode and the build was accepted.

**Comment by sdushay** [comment]
Thanks for pointing this out.  It should be fixed in v1.1.3
