### ISSUE TITLE
iOS 10 aborts

### ISSUE THREAD

**Issue by Goosaroo** [wymsee/cordova-imagePicker#182]
Hi Guys,

Thanks for the great plugin, it works like a charme on iOS8 and iOS9.

However on the iOS10 emulator the app aborts on the instant I try to open the image gallery(haven't tested it on a proper device). The plugin is installed with the NSPhotoLibraryUsageDescription extension which is present in plugin.xml

Logs:
Sep 29 13:42:12 MacBook-Pro com.apple.CoreSimulator.SimDevice.ABD1B0F8-A3D2-4450-9062-4226F0C23E73.launchd_sim[24069] (UIKitApplication:com.ionicframework.ionicsidemenu[0xe78f][24330]): Service exited due to Abort trap: 6
Sep 29 13:42:12 MacBook-Pro backboardd[24087]: [Common] Unable to get short BSD proc info for 24330: No such process
Sep 29 13:42:12 MacBook-Pro backboardd[24087]: [Common] Unable to get proc info for 24330: No such process
Sep 29 13:42:12 MacBook-Pro assertiond[24090]: notify_suspend_pid() failed with error 7

Any ideas?

Kind regards, Gijs

**Comment by januslo** [comment]
You can set by installation var just install another plugin about this issue. Check my repository 

发自我的 iPhone

**Comment by Goosaroo** [comment]
Hi Januslo,

The plugin is installed with: cordova plugin add cordova-plugin-image-picker --variable PHOTO_LIBRARY_USAGE_DESCRIPTION="your message"... but the problem persists. 

I have tried copying the files in your repository but that doesnt work. Was that your suggestion?

Thanks for your help, Gijs

**Comment by januslo** [comment]
Oh, sorry. Just forgot I have never try in the simulator. Have you tried in your phone?

发自我的 iPhone

**Comment by Goosaroo** [comment]
Just tried it in the ionic-view app with IOS 10 and works perfect. Strange that the emulator isnt working. But at least the real device works.

Thanks for the support. G

**Comment by bmwertman** [comment]
I also have the following in my `myApp.info.plist` 

`<key>NSPhotoLibraryUsageDescription</key>`
` <string>Setting profile pictures and sharing images with school parents</string>`

But on my iPhone 5 running ios 10 I get the error;

`Album Error: user denied access - (null)`

Do you have a fix for this?

**Comment by januslo** [comment]
Uninstall the app before you install the new one. To ensure the setting is reset.

发自我的 iPhone

**Comment by bmwertman** [comment]
OK that worked, thanks. 

Is there a way to have the user grant permission to use their images at app install? 

I get a popup the first time the app tries to access images.

**Comment by prateek-js** [comment]
Is there a way to ask for Permission if user has disallowed it the first time or in settings.
As of now it shows some message "Album Error: user denied access - (null)". Or can we show the popup how it comes in camera plugin
