### ISSUE TITLE
PhoneGap Build fails with CLI 8.0.0 (Android Platform 7.0.0)

### ISSUE THREAD

**Issue by mkihellas** [wymsee/cordova-imagePicker#263]
Hello there,
We are trying to update our App from Cordova CLI 7.1.0 to 8.0.0 and it seems that cordova-imagePicker plugin causes the build to fail on Android. 

Looks like the problem is that you are using the **source-file** tag for images instead of the **resource-file** tag on plugin.xml.
![example](https://user-images.githubusercontent.com/35369394/36792655-cfc5903a-1ca3-11e8-9357-ca83c70021c7.PNG)

We checked all our 3rd party plugins and they are handling images using the resource-file tag. For example: 
![example2](https://user-images.githubusercontent.com/35369394/36793240-8ff6d0a2-1ca5-11e8-8134-2e8002945834.PNG)

When we remove the cordova-imagePicker plugin, the build succeeds.
More info can be found in this discussion here: https://forums.adobe.com/thread/2445961

Is there any chance to update your plugin and use the resource-file tag for images on plugin.xml, so we will be able to build with CLI 8.0.0?

**Comment by mkihellas** [comment]
I made it work in my repo: https://github.com/mkihellas/cordova-imagePicker
I changed all the source-file regarding xml and png files to **resource-file** and PhoneGap builds successfully for Android with CLI 8.0.0

HINT: I had also to do some changes in ImageFetcher.java.
mkihellas/cordova-imagePicker@61c18fc
Check https://github.com/wymsee/cordova-imagePicker/issues/262 for more info.

**Comment by christianidas** [comment]
This should not be closed, right?  Shouldn't it remain open until it has been fixed and versioned in the plugin?

**Comment by rafaelmb** [comment]
It should. But this repo is 2 years without update. And the issue owner decided to close, no interaction from the developers.
