### ISSUE TITLE
Update Phone Gap Build Plugin Repository

### ISSUE THREAD

**Issue by anemitoff** [wymsee/cordova-imagePicker#36]
Is it possible to release a new version for Phone Gap Build?
Also... Thanks so much for your efforts!

**Comment by TheKiteEatingTree** [comment]
It seems I can't update the version there anymore. You should be able to use this instead:
http://plugins.cordova.io/#/package/com.synconset.imagepicker

Details are here: http://phonegap.com/blog/2014/12/09/phonegap-build-new-features/
