### ISSUE TITLE
How to use this plugin

### ISSUE THREAD

**Issue by borhademohini** [wymsee/cordova-imagePicker#39]
Hello all,

I want to use this plugin in my app.

I have included "<gap:plugin name="com.synconset.imagepicker" />" in my config file.

and called this function getPictures()
{
	alert('getPictures ');
	window.imagePicker.getPictures(
		function(results) {
			for (var i = 0; i < results.length; i++) {
				alert('Image URI: ' + results[i]);
			}
		}, function (error) {
				alert('Error: ' + error);
		}
	);
}

on click event of the button.

But nothing happens.

Where I am going wrong.

Additionally I have included <script src="libs/imagepicker.js"></script> in the index file.

Please help me to get this solved.

Any help would be appreciated.

Thanks.

**Comment by khanshakeeb** [comment]
How I will use this plugin?

as I have understand to put input type = file field and it will run automatically?

Thanks
