### ISSUE TITLE
Update version for build.phonegap.com

### ISSUE THREAD

**Issue by BluTiGeS** [wymsee/cordova-imagePicker#42]
I would ppreciate it if you update the version to our latest 1.0.5 .

At the moment 1.0.4 is latest.

Can you please update it ? Many Thanks.

Link to the reference page:
https://build.phonegap.com/plugins/807

**Comment by TheKiteEatingTree** [comment]
It seems I can't update the version there anymore.  You should be able to use this instead:
http://plugins.cordova.io/#/package/com.synconset.imagepicker

Details are here: http://phonegap.com/blog/2014/12/09/phonegap-build-new-features/

**Comment by BluTiGeS** [comment]
Thanks for your hint but now I am getting build erros,

also adding the plugin via cordova results in not found error:

CMD:
cordova plugin add com.synconset.imagepicker

Result:
Fetching plugin "com.synconset.imagepicker" via plugin registry
npm ERR! fetch failed http://registry.cordova.io/com.synconset.imagepicker/-/com.synconset.imagepicker-1.0.6.tgz
Error: 404 Not Found

**Comment by BluTiGeS** [comment]
Also now seeing SHA Checksum issue
Fetching plugin "com.synconset.imagepicker" via plugin registry
Error: shasum check failed for C:\Users\MyUser\AppData\Local\Temp\npm-5144-E8GMsWi1\registry.cordova.io\com.synconset.imagepicker\-\com.synconset.im
agepicker-1.0.6.tgz

**Comment by TheKiteEatingTree** [comment]
The 404 was an issue with my new submission to the registry.  I resolved that issue shortly before your comment about the checksum issue.  I'm not sure what to make of the new issue.  I did a quick test and it seemed to fetch the plugin ok for me.  Has anyone else had any issues or success installing from the registry?

**Comment by BluTiGeS** [comment]
Hi,

The build.phonegab.com now works. 

But still getting hash error. 

But I can work with it.  

Thanks

**Comment by BluTiGeS** [comment]
Hi,

i have retested today now it works flawless.
Maybe some server cache issue.

Many Thanks
