### ISSUE TITLE
IOS8.3 not supported

### ISSUE THREAD

**Issue by atom2ueki** [wymsee/cordova-imagePicker#58]
The following build commands failed:
	CompileXIB testapp/Resources/ELCAlbumPickerController.xib
	CompileXIB testapp/Resources/ELCAssetPicker.xib
	CompileXIB testapp/Resources/ELCAssetTablePicker.xib
	CpResource testapp/Resources/Overlay.png build/emulator/testapp.app/Overlay.png
(4 failures)

**Comment by CSullivan102** [comment]
Haven't seen this issue myself, it looks like maybe those files aren't where XCode is expecting them to be?

**Comment by atom2ueki** [comment]
@CSullivan102 I recreate the whole project, it works this time, but when trigger getPictures functions, seems no response send back... strange

**Comment by atom2ueki** [comment]
@CSullivan102 Sorry my bad, I can't see the log, because i never enable console log in my emulator
