### ISSUE TITLE
iOS 8.3 issue

### ISSUE THREAD

**Issue by jaredthomas1** [wymsee/cordova-imagePicker#60]
works perfectly on my app for android, however for iOS just throws error "index.html  TypeError: undefined is not an object (evaluating 'window.imagePicker.getPictures')

**Comment by CSullivan102** [comment]
Looks like the plugin hasn't been initialized properly, are you sure you added the plugin for iOS as well as for Android?

**Comment by jaredthomas1** [comment]
I have a single project for both platforms, added <gap:plugin name="com.synconset.imagepicker" version="1.0.4" /> to config.xml and built each native package. worked for android, didn't work for iOS.

**Comment by jaredthomas1** [comment]
resolved by recreating ios application template. thanks for response.

**Comment by CSullivan102** [comment]
No problem, glad it's fixed!
