### ISSUE TITLE
Translations errors in cordova 5

### ISSUE THREAD

**Issue by rodrigograca31** [wymsee/cordova-imagePicker#66]
Hi!
This plugin is missing some translations....
With the latest cordova (that uses gradle) it generates errors and fails to build...

**Solutions:**
1. Set an empty value: `<string name="discard"></string>` in all of the missing translatins, for exemple: `src/android/Library/res/values-de/multiimagechooser_strings_de.xml`
2. Set a default: `<string name="discard">NOT TRANSLATED</string>` in all of the missing translatins, for exemple: `src/android/Library/res/values-de/multiimagechooser_strings_de.xml`
3. Use the google translator translations: `<string name="discard">Stornieren</string>` in all of the missing translatins, for exemple: `src/android/Library/res/values-de/multiimagechooser_strings_de.xml`
4. Ignore it: `<resources xmlns:tools="http://schemas.android.com/tools" tools:ignore="MissingTranslation" >` in `src/android/Library/res/values/multiimagechooser_strings_en.xml`
5. Delete all the translations: in `src/android/Library/res/`delete all the folders matching this "values-*"

I can make a pull request with one of the solutions.,
**What would be the best way to solve this problem?**

Some debug/errors shown:
```
...
:mergeReleaseResources UP-TO-DATE
:processReleaseManifest UP-TO-DATE
:processReleaseResources UP-TO-DATE
:generateReleaseSources UP-TO-DATE
:compileReleaseJava UP-TO-DATE
:lintVitalRelease/home/unknown/myApp/platforms/android/res/values/multiimagechooser_strings_en.xml:7: Error: "discard" is not translated in "es" (Spanish), "fr" (French), "hu" (Hungarian), "ja" (Japanese), "ko" (Korean) [MissingTranslation]
    <string name="discard">Cancel</string>
            ~~~~~~~~~~~~~~
/home/unknown/myApp/platforms/android/res/values/multiimagechooser_strings_en.xml:8: Error: "done" is not translated in "es" (Spanish), "fr" (French), "hu" (Hungarian), "ja" (Japanese), "ko" (Korean) [MissingTranslation]
    <string name="done">OK</string>
            ~~~~~~~~~~~
/home/unknown/myApp/platforms/android/res/values/strings.xml:3: Error: "app_name" is not translated in "de" (German), "es" (Spanish), "fr" (French), "hu" (Hungarian), "ja" (Japanese), "ko" (Korean) [MissingTranslation]
    <string name="app_name">myApp</string>
            ~~~~~~~~~~~~~~~
/home/unknown/myApp/platforms/android/res/values/strings.xml:4: Error: "launcher_name" is not translated in "de" (German), "es" (Spanish), "fr" (French), "hu" (Hungarian), "ja" (Japanese), "ko" (Korean) [MissingTranslation]
    <string name="launcher_name">@string/app_name</string>
            ~~~~~~~~~~~~~~~~~~~~
/home/unknown/myApp/platforms/android/res/values/strings.xml:5: Error: "activity_name" is not translated in "de" (German), "es" (Spanish), "fr" (French), "hu" (Hungarian), "ja" (Japanese), "ko" (Korean) [MissingTranslation]
    <string name="activity_name">@string/launcher_name</string>
            ~~~~~~~~~~~~~~~~~~~~

   Explanation for issues of type "MissingTranslation":
   If an application has more than one locale, then all the strings declared
   in one language should also be translated in all other languages.

   If the string should not be translated, you can add the attribute
   translatable="false" on the <string> element, or you can define all your
   non-translatable strings in a resource file called donottranslate.xml. Or,
   you can ignore the issue with a tools:ignore="MissingTranslation"
   attribute.

   By default this detector allows regions of a language to just provide a
   subset of the strings and fall back to the standard language strings. You
   can require all regions to provide a full translation by setting the
   environment variable ANDROID_LINT_COMPLETE_REGIONS.

   You can tell lint (and other tools) which language is the default language
   in your res/values/ folder by specifying tools:locale="languageCode" for
   the root <resources> element in your resource file. (The tools prefix
   refers to the namespace declaration http://schemas.android.com/tools.)

5 errors, 0 warnings
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lintVitalRelease'.
> Lint found fatal errors while assembling a release target.
  
  To proceed, either fix the issues identified by lint, or modify your build script as follows:
  ...
  android {
      lintOptions {
          checkReleaseBuilds false
          // Or, if you prefer, you can continue to check for errors in release builds,
          // but continue the build even when errors are found:
          abortOnError false
      }
  }
  ...

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by yleflour** [comment]
Considering the fact that the plugin is translated in each language, I think it is fair to assume that the buttons should be translated too.

But this only solves part of the issue as some of the translation errors concern the app_name, activity_name and launcher_name meaning that as soon as translations are included by one plugin your app build will break as it will require translation for the other strings. So to fix the second part I believe the best solution is to add `translatable="false"`to each of your string in strings.xml.

**Comment by radzserg** [comment]
+1 I use ionicframework. And have the same when trying to ionic build android --release. I think it's not a big deal to add missed data.

**Comment by alzalabany** [comment]
where to add these lines ? im using ionic too and it fail to build --release

**Comment by david-yoshi** [comment]
Having same problem. Building signed APK fails.

platforms/android/res/values/multiimagechooser_strings_en.xml

Error:(7) Error: "discard" is not translated in "de" (German), "es" (Spanish), "fr" (French), "hu" (Hungarian), "ja" (Japanese), "ko" (Korean) [MissingTranslation]

Error:(8) Error: "done" is not translated in "de" (German), "es" (Spanish), "fr" (French), "hu" (Hungarian), "ja" (Japanese), "ko" (Korean) [MissingTranslation]

Error:(3) Error: "app_name" is not translated in "de" (German), "es" (Spanish), "fr" (French), "hu" (Hungarian), "ja" (Japanese), "ko" (Korean) [MissingTranslation]

Error:(4) Error: "launcher_name" is not translated in "de" (German), "es" (Spanish), "fr" (French), "hu" (Hungarian), "ja" (Japanese), "ko" (Korean) [MissingTranslation]

Error:(5) Error: "activity_name" is not translated in "de" (German), "es" (Spanish), "fr" (French), "hu" (Hungarian), "ja" (Japanese), "ko" (Korean) [MissingTranslation]

**Comment by morfair** [comment]
How to do correct translate?

**Comment by rodrigograca31** [comment]
@morfair @david-yoshi @alzalabany 

In my first post I gave 4 solutions that you guys can use accordingly to your taste...

**Comment by david-yoshi** [comment]
Need more detail on how to do it. What files need to be edited etc. For example I finally fixed it by adding

lintOptions {
    disable 'MissingTranslation'
}

to the android{} block in build.gradle

**Comment by rodrigograca31** [comment]
I just edited my first post with the files paths and added a fifth solution...

Tip: I stopped using this plugin and used `cordova-plugin-camera` if I remember correctly it was because this one was crashing in some devices...

**Comment by jiuyuehe** [comment]
这种半吊子水平还搞什么国际化，去掉src/android/Library/res/下面的各种语言。配置文件即可
