### ISSUE TITLE
how to get base64

### ISSUE THREAD

**Issue by wuyuedefeng** [wymsee/cordova-imagePicker#68]
I has get URI (  console.log('Image URI: ' + results[i]); )  ,but I want to get base64 data, how to transfer??

**Comment by hanssens** [comment]
This is not specifically something that the plugin should do for you, but [the same question is on SO](http://stackoverflow.com/questions/11188599/using-phonegap-how-to-get-base64-image-data-of-the-photo-chosen-from-photo-libr) as well. Accepted answer seems to be:

    function encodeImageUri(imageUri)
    {
         var c=document.createElement('canvas');
         var ctx=c.getContext("2d");
         var img=new Image();
         img.onload = function(){
           c.width=this.width;
           c.height=this.height;
           ctx.drawImage(img, 0,0);
         };
         img.src=imageUri;
         var dataURL = c.toDataURL("image/jpeg");
         return dataURL;
    }

Does this work for you as well?

**Comment by wuyuedefeng** [comment]
it works well,thank you very much!
