### ISSUE TITLE
Images turning sideways/upside down on upload

### ISSUE THREAD

**Issue by garrydelacruz** [wymsee/cordova-imagePicker#7]
I am using this plugin and it works great! I encountered one issue though. Photos are displayed in the correct orientation, however, when it gets uploaded to a server, some are showing sideways/upside down. (I am testing on Android)

I saw the below stackoverflow entry and it seems the solution is by using the camera option correctOrientation: true. 

http://stackoverflow.com/questions/9353629/images-turning-sideways-upside-down-after-being-uploaded-via-phonegap-ios

In your plugin, is it possible to add correctOrientation as part of the options?

**Comment by ZalmanBlau** [comment]
I'm still having this issue in plugin version 1.1.1.
iOS version 9.3.2

Anybody else on the same boat?

**Comment by blablapolicja** [comment]
+1

**Comment by sxxymzy** [comment]
+1

**Comment by kiddrew** [comment]
+1

**Comment by heks** [comment]
+1

**Comment by ariel-ibarra-jd** [comment]
Same problem here with iOS
