### ISSUE TITLE
success() callback is called immediately

### ISSUE THREAD

**Issue by sdsaunders** [wymsee/cordova-imagePicker#78]
I am testing on a Nexus 4 & 7.  Works as expected on an iPhone 6.

Javascript looks like this:

window.imagePicker.getPictures(
    			    function(results) {
    			    	
    			    	console.log( "result =  " + JSON.stringify( results ) );

    			    	if( results.length > 0 && results[0].length > 0 ) 
    			    		app.set_map_image ( results[0] );	
    			    	}
    			    }, function (error) {
    			        console.log('Error: ' + error);
    			    }, {
    			        maximumImagesCount: 1,
    			        width: 400,
    			        quality: 50,
    			        outputType: imagePicker.OutputType.FILE_URI
    			    }
    			);

The console shows result = [] as soon as getPictures() is called, then the image picker displays.  After selecting, and 'processing' one image the picker closes and the success callback is not called.

Some of the log file might be relevant to helping figure this out:
I/chromium(19920): [INFO:CONSOLE(114)] "result = []", source: file:///android_asset/www/js/index.js (114)
I/ActivityManager(  604): Displayed com.madmicos.tacticalAdvisor/com.synconset.MultiImageChooserActivity: +161ms (total +319ms)
I/ActivityManager(  604): Timeline: Activity_windows_visible id: ActivityRecord{42a21b00 u0 com.madmicos.tacticalAdvisor/com.synconset.MultiImageChooserActivity t38} time:8144845
I/Keyboard.Facilitator(  830): onFinishInput()
I/ActivityManager(19920): Timeline: Activity_idle id: android.os.BinderProxy@42096740 time:8144923
I/ActivityManager(19920): Timeline: Activity_idle id: android.os.BinderProxy@4197f0d8 time:8144923
I/ActivityManager(  604): Timeline: Activity_windows_visible id: ActivityRecord{42521928 u0 com.madmicos.tacticalAdvisor/com.synconset.MultiImageChooserActivity t38} time:8145177
W/InputMethodManagerService(  604): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@420bf198 attribute=null, token = android.os.BinderProxy@4219c6c8
I/Keyboard.Facilitator(  830): onFinishInput()
I/ActivityManager(19920): Timeline: Activity_idle id: android.os.BinderProxy@4197f0d8 time:8154595
I/ActivityManager(  604): Timeline: Activity_windows_visible id: ActivityRecord{42a21b00 u0 com.madmicos.tacticalAdvisor/com.synconset.MultiImageChooserActivity t38} time:8154936
W/InputMethodManagerService(  604): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@42061a18 attribute=null, token = android.os.BinderProxy@42bbf870
D/CordovaInterfaceImpl(19920): Sending activity result to plugin
W/CordovaPlugin(19920): Attempted to send a second callback for ID: ImagePicker135475846
W/CordovaPlugin(19920): Result was: ["file:\/\/\/data\/data\/com.madmicos.tacticalAdvisor\/cache\/Screenshot_2015-07-11-12-00-28-745357904.png"]
W/CordovaInterfaceImpl(19920): Got an activity result, but no plugin was registered to receive it.

**Comment by krzykz** [comment]
Any news on this? Having the same problem.
