### ISSUE TITLE
Preserving EXIF

### ISSUE THREAD

**Issue by brizdotdev** [wymsee/cordova-imagePicker#89]
Is there a way to preserve EXIF in the copy created ?

**Comment by mattchete** [comment]
I'm interested in that too.

**Comment by JoshuaGRubin** [comment]
+1!  This is so close to being an excellent drop-in replacement for the library mode of the Cordova camera plugin, but I need the EXIF information as well.  An option to return the raw image's URIs- or at least URIs to an unmanipulated copy of the raw image with EXIF intact (in the case where no manipulation was requested) would solve this for me.  Then your user would have the option to extract EXIF and manipulate the image afterwords using the canvas.  Otherwise, great work!

**Comment by mattchete** [comment]
I'm now using this fork of the plugin:
https://github.com/pawee/snw-cordova-imagePicker

I've patched it so it returns the path of the original images on the device (and not a copy like the plugin does). That way you have access to everything from the original image, including exif.

My 2 patches (ios and android) are there:
http://infinit.io/_/Z3BiRnv

**Comment by JoshuaGRubin** [comment]
Thanks so much, mattchete, and for the quick reply - that worked beautifully!

**Comment by ykarthikreddy18** [comment]
Hi @mattchete .. Can u plz help me on how to patch your files..

**Comment by ykarthikreddy18** [comment]
Hi @mattchete .. Ur patch worked great.. But the small problem is im gettitng the location as /storage/sdcard0/DCIM/IMG_5245.JPG... Im doing           window.resolveLocalFileSystemURL(fileURI, copyFile, fail); but Im getting an error 

11-26 14:05:46.080: W/PluginManager(3111): THREAD WARNING: exec() call to File.resolveLocalFileSystemURI blocked the main thread for 52ms. Plugin should use CordovaInterface.getThreadPool().
11-26 14:05:46.082: W/System.err(3111): java.net.MalformedURLException: No installed handlers for this URL
11-26 14:05:46.082: W/System.err(3111): 	at org.apache.cordova.file.FileUtils.resolveLocalFileSystemURI(FileUtils.java:630)
11-26 14:05:46.082: W/System.err(3111): 	at org.apache.cordova.file.FileUtils.access$400(FileUtils.java:52)
11-26 14:05:46.082: W/System.err(3111): 	at org.apache.cordova.file.FileUtils$14.run(FileUtils.java:389)
11-26 14:05:46.082: W/System.err(3111): 	at org.apache.cordova.file.FileUtils$25.run(FileUtils.java:555)
11-26 14:05:46.082: W/System.err(3111): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-26 14:05:46.082: W/System.err(3111): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-26 14:05:46.082: W/System.err(3111): 	at java.lang.Thread.run(Thread.java:818)

Do u have any idea regarding this error?

**Comment by mattchete** [comment]
No idea, I'm using directly the path as "/storage/sdcard0/DCIM/IMG_5245.JPG", never used resolveLocalFileSystemURL().

**Comment by ykarthikreddy18** [comment]
Thnku for your reply @mattchete

**Comment by JoshuaGRubin** [comment]
Just to check-in again, any plans of a adding a raw mode to cordovan-image-picker?  Would still love to have multi+select that returns paths to unprocessed images (with exif) from their original gallery locations.

**Comment by moritzschaefer** [comment]
+1

**Comment by moritzschaefer** [comment]
@mattchete Would you mind forking and adding your patches as a commit? Your patch-link is not available anymore

**Comment by mattchete** [comment]
@moritzschaefer Sorry I don't have it anymore

**Comment by moritzschaefer** [comment]
@mattchete all right no worries. I just used "useOriginal=true" from https://github.com/pawee/snw-cordova-imagePicker which also preserves EXIF data.

**Comment by matthieu80** [comment]
@mattchete 
https://github.com/pawee/snw-cordova-imagePicker is the best plugin to do the job, thank you! There is just one problem, I get the "plugin_not_installed" on android. Package.json is missing, but when I create one I still have the problem.

**Comment by techaffinity** [comment]
Hi, Yes there is no package.json file in https://github.com/pawee/snw-cordova-imagePicker. We need your support for integrate image picker plugin for Exif data.
